title: Anna's Website
author: Anna
email: acecil2@byu.edu
description: > # this means to ignore newlines until "baseurl:"
  This is just practice to learn more about github pages, nothing to see here
theme: minima
# social links
github_username:  anna-ce # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
